version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexusdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
      npm run generate -w db &&
      npm run migrate -w db &&
      npm run seed -w db
      "

    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/nexusdb?sslmode=disable

  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - migrate
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/nexusdb?sslmode=disable
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    depends_on:
      - migrate
      - server
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/nexusdb?sslmode=disable
      SERVER_URL: http://server:4000/internal/deliver

  subscriber_accounting:
    build:
      context: .
      dockerfile: subscribers/accounting/Dockerfile
    ports:
      - "5001:5001"

  subscriber_shipping:
    build:
      context: .
      dockerfile: subscribers/shipping/Dockerfile
    ports:
      - "5002:5002"

volumes:
  postgres_data:
